- name: Download CloudConductor CLI
  git: repo=https://github.com/cloudconductor/cloud_conductor_cli.git dest={{ home_dir}}/cloudconductor_cli

- name: Bundele Install
  command: bundle install chdir={{ home_dir}}/cloudconductor_cli

- name: Bundle exec rake install
  command: bundle exec rake install chdir={{ home_dir}}/cloudconductor_cli

- name: Setting CloudConductor Information
  lineinfile: dest={{ home_dir}}/.bashrc line="export CC_HOST=localhost"
- lineinfile: dest={{ home_dir}}/.bashrc line="export CC_PORT=8080"
- lineinfile: dest={{ home_dir}}/.bashrc line="export CC_AUTH_ID=cloudconductor@example.com"
- lineinfile: dest={{ home_dir}}/.bashrc line="export CC_AUTH_PASSWORD=cloudconductor"
